baseURL = "https://manishj2007.github.io/"
languageCode = "en-us"
title = "Manish J · Portfolio"
theme = "PaperMod"

[params]
  defaultTheme = "auto"
  ShowReadingTime = true

[menu]
  [[menu.main]]
    name = "About"
    url  = "/about/"
    weight = 1

